server:
  port: 8080

spring:
  application:
    name:
      curimbex
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:curimbex}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  packagesToScan: com.murilonerdx.curimbex.controller
  swagger-ui:
    path: /docs-curimbex.html
  api-docs:
    path: /docs-curimbex